### ISSUE TITLE
Repetition of sub elements possible? Or need to specialize?

### ISSUE THREAD

**Issue by remybernard** [NIEM/Implementation-Cookbook#2]
Hi,
I’m not sure if this question should be placed in this forum. If not please let me know where I should ask it.

I’m not sure if it’s possible to either repeat sub-elements, or substitute abstract elements multiple times and stay NIEM conformant. E.g., if I have an exchange requirement where I must model the following:
- PersonBirthLocation’s State code
- PersonBirthLocation’s State name
- PersonBirthLocation’s Country Name
- PersonBirthLocation’s Country Code

These would be part of the nc:PersonBirthLocation/nc:Address (substituted for nc:LocationAddressAbstract) but would require to use multiple times the abstract sub-elements nc:LocationState and nc:LocationCountry (both within nc:Address). As follows:
- PersonBirthLocation’s State code = nc:PersonBirthLocation/nc:Address/(nc:LocationState)nc:LocationStateFIPS5-2NumericCode
- PersonBirthLocation’s State name = nc:PersonBirthLocation/nc:Address/(nc:LocationState)nc:LocationStateName
- PersonBirthLocation’s Country Name = nc:PersonBirthLocation/nc:Address/(nc:LocationCountry)nc:LocationCountryName
- PersonBirthLocation’s Country Code = nc:PersonBirthLocation/nc:Address/(nc:LocationState)nc:LocationCountryISO3166Alpha2Code

Is this possible? Or would I have to extend the nc:PersonBirthLocation to specifically add the number of elements that I want?

Thanks for your help

**Comment by webb** [comment]
It's perfectly OK to substitute an element different ways multiple times. Basically, the XML Schema says it  is OK, and NIEM doesn't say otherwise. 

If you want to restrict content, there are a few ways to do it: (1) Build a NIEM subset, using something like the SSGT, that includes only the content you need with the # of occurrences you need. (2) Build Schematron rules that restrict the content to what you need. (3) Build a constraint schema that restricts the base content down to what you need.

Of these, (1) is easy, (2) requires some XPath knowledge & tooling, and (3) is likely hand-edited XSD. (1) and (2) is recommended, and (3) is only recommended if you have specific tool requirements for it (like trying to get the exact content model into JAXB objects).

Hope this helps!

I'm closing this issue. Please feel free to reopen if you'd like to dig further!
